title: GUANGDONGGUNIANG
author: WUTIAOREN
email: wutiaoren@haifeng.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  WUTIAOREN wutiaoren haifeng

# social links
twitter_username: wutiaoren # DO NOT include the @ character, or else the build will fail!
github_username:  wutiaoren # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
